=== cloudstoragesec/antivirus-for-amazon-s3-terraform/app_config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Configuration for CloudStorageScan",
  "type": "object",
  "required": [
    "objectTagKeys",
    "quarantine",
    "scanList",
    "skipList",
    "classifyList",
    "classifySkipList",
    "scanTaggingEnabled",
    "scanTagsExcluded",
    "classificationTaggingEnabled",
    "classificationTagsExcluded"
  ],
  "properties": {
    "scanTaggingEnabled": {
      "type": "boolean",
      "description": "Indicates whether tags should be added to the scanned objects."
    },
    "scanTagsExcluded": {
      "type": "array",
      "description": "Scan tags to not be added to scanned objects",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "additionalProperties": false
    },
    "classificationTaggingEnabled": {
      "type": "boolean",
      "description": "Indicates whether tags should be added to the classified objects."
    },
    "classificationTagsExcluded": {
      "type": "array",
      "description": "Classification tags to not be added to classified objects",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "additionalProperties": false
    },
    "avEventProtectedBuckets": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "additionalProperties": false
    },
    "avScheduledBuckets": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "additionalProperties": false
    },
    "efsClassificationRuleSets": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "additionalProperties": false
        }
      }
    },
    "dcEventBucketRuleSets": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "additionalProperties": false
        }
      }
    },
    "ebsClassificationRuleSets": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "additionalProperties": false
        }
      }
    },
    "fsxClassificationRuleSets": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "additionalProperties": false
        }
      }
    },
    "classificationRuleSets": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "additionalProperties": false
        }
      }
    },
    "objectTagKeys": {
      "type": "object",
      "required": [
        "result",
        "dateScanned",
        "virusName",
        "virusUploadedBy",
        "errorMessage",
        "classificationResult",
        "dateClassified",
        "classificationMatches",
        "classificationErrorMessage"
      ],
      "properties": {
        "result": {
          "type": "string",
          "description": "The tag key for scan results."
        },
        "dateScanned": {
          "type": "string",
          "description": "The tag key for the scan date."
        },
        "virusName": {
          "type": "string",
          "description": "The tag key for the virus name."
        },
        "virusUploadedBy": {
          "type": "string",
          "description": "The tag key for who uploaded the virus."
        },
        "errorMessage": {
          "type": "string",
          "description": "The tag key for the error message."
        },
        "classificationResult": {
          "type": "string",
          "description": "The tag key for classification results."
        },
        "dateClassified": {
          "type": "string",
          "description": "The tag key for the classification date."
        },
        "classificationMatches": {
          "type": "string",
          "description": "The tag key for the list of classification matches found."
        },
        "classificationErrorMessage": {
          "type": "string",
          "description": "The tag key for the classification error message."
        }
      }
    },
    "quarantine": {
      "type": "object",
      "required": [
        "action",
        "moveBucketPrefix"
      ],
      "properties": {
        "action": {
          "type": "string",
          "pattern": "Keep|Move|Delete",
          "description": "Action to take on an object upon a virus being detected."
        },
        "moveBucketPrefix": {
          "type": "string",
          "description": "Bucket to move infected objects to."
        }
      }
    },
    "scanList": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "additionalProperties": false
        }
      }
    },
    "skipList": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "additionalProperties": false
        }
      }
    },
    "classifyList": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "additionalProperties": false
        }
      }
    },
    "classifySkipList": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "additionalProperties": false
        }
      }
    },
    "twoBucketConfig": {
      "type": "object",
      "properties": {
        "regions": {
          "type": "object",
          "patternProperties": {
            "^(us(-gov)?|af|ap|ca|cn|eu|me|sa)-(central|(north|south)?(east|west)?)-[1-9]$": {
              "type": "object",
              "properties": {
                "destinationBucket": {
                  "type": "string",
                  "description": "The bucket to move files to"
                },
                "destinationPrefix": {
                  "type": "string",
                  "description": "The prefix to use within the destination bucket"
                }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        },
        "buckets": {
          "type": "object",
          "patternProperties": {
            "^[a-zA-Z0-9-._]{1,255}$": {
              "type": "object",
              "properties": {
                "destinationBucket": {
                  "type": "string",
                  "description": "The bucket to move files to"
                },
                "destinationPrefix": {
                  "type": "string",
                  "description": "The prefix to use within the destination bucket"
                }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== cloudstoragesec/antivirus-for-amazon-s3-terraform/app_config_doc.json
{
    "scanTaggingEnabled": true,
    "scanTagsExcluded":
    [],
    "classificationTaggingEnabled": true,
    "classificationTagsExcluded":
    [],
    "objectTagKeys":
    {
        "result": "scan-result",
        "dateScanned": "date-scanned",
        "virusName": "virus-name",
        "virusUploadedBy": "uploaded-by",
        "errorMessage": "message",
        "classificationResult": "classification-result",
        "dateClassified": "date-classified",
        "classificationMatches": "classification-matches",
        "classificationErrorMessage": "classification-message"
    },
    "quarantine":
    {
        "action": "Move",
        "moveBucketPrefix": "cloudstoragesecquarantine-${app_id}"
    },
    "scanList":
    {},
    "skipList":
    {},
    "classifyList":
    {},
    "classifySkipList":
    {}
}
